export const ROUTE_NAMES = Object.freeze({
  login: 'loginPage',
  signUp: 'signUpPage',
  clerkLogin: 'clerkLoginPage',
  acceptInvitation: 'acceptInvitationPage',
  customSignUp: 'customSignUpPage',
  postLogin: 'postLoginPage',
  handleSignIn: 'handleSignInPage',
  requestPending: 'requestPendingPage',
  accountDeactivated: 'accountDeactivatedPage',
  adminDashboard: 'adminDashboardPage',
  dashboard: 'dashboardPage',
  borrowerMyReservations: 'borrowerMyReservationsPage',
  borrowerCreateReservation: 'borrowerCreateReservationPage',
  borrowerViewReservationList: 'borrowerViewReservationListPage',
  borrowerApprovedRequestsLogs: 'borrowerApprovedRequestsLogsPage',
  borrowerPendingRequestsLogs: 'borrowerPendingRequestsLogsPage',
  borrowerCompletedReservationsLogs: 'borrowerCompletedReservationsLogsPage',
  settings: 'settingsPage',
  facultyDashboard: 'facultyDashboardPage',
});
