name: "TechReserve"

services:
  backend:
    build:
      context: ./backend
    container_name: techreserve_backend
    volumes:
      - ./backend:/app
      - backend_var:/app/var
      - backend_vendor:/app/vendor
    env_file:
      - .env
    ports:
      - "${BACKEND_EXTERNAL_PORT}:8000"
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?serverVersion=15&charset=utf8"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: sync+restart
          path: ./backend/composer.json
          target: /app/composer.json
        - action: sync+restart
          path: ./backend/composer.lock
          target: /app/composer.lock

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: techreserve_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@techreserve.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_EXTERNAL_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  frontend:
    build:
      context: ./frontend
    container_name: techreserve_frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"
      VITE_API_BASE_URL: "http://localhost:8000"
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:5173"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: sync+restart
          path: ./frontend/package.json
          target: /app/package.json
        - action: sync+restart
          path: ./frontend/package-lock.json
          target: /app/package-lock.json

volumes:
  frontend_node_modules:
  backend_var:
  backend_vendor:
  pgadmin_data:
