<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260626010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create durable TextBee SMS message delivery logs.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("
            CREATE TABLE IF NOT EXISTS sms_message_logs (
                sms_message_log_identifier BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                provider VARCHAR(40) DEFAULT 'TextBee' NOT NULL,
                message_source VARCHAR(50) NOT NULL,
                task_identifier INT DEFAULT NULL,
                assigned_to_account_id INT DEFAULT NULL,
                provider_message_id VARCHAR(255) DEFAULT NULL,
                message TEXT NOT NULL,
                recipients JSONB NOT NULL,
                delivery_status VARCHAR(50) NOT NULL,
                provider_created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                response_payload JSONB DEFAULT NULL,
                error_message TEXT DEFAULT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NOW() NOT NULL,
                PRIMARY KEY (sms_message_log_identifier)
            )
        ");
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_SMS_MESSAGE_LOG_STATUS_CREATED ON sms_message_logs (delivery_status, created_at)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_SMS_MESSAGE_LOG_SOURCE_CREATED ON sms_message_logs (message_source, created_at)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_SMS_MESSAGE_LOG_TASK ON sms_message_logs (task_identifier)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_SMS_MESSAGE_LOG_PROVIDER_ID ON sms_message_logs (provider_message_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS sms_message_logs');
    }
}
