<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260527020000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add account action log snapshot table and enforce unique account ID numbers';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_ACCOUNTS_ID_NUMBER_NOT_BLANK ON accounts (id_number) WHERE id_number IS NOT NULL AND BTRIM(id_number) <> \'\'');

        $this->addSql('CREATE TABLE IF NOT EXISTS account_action_logs (
            account_action_log_identifier INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            employee_id_number VARCHAR(50) NOT NULL,
            clerk_user_id VARCHAR(255) DEFAULT NULL,
            first_name VARCHAR(50) NOT NULL,
            last_name VARCHAR(50) NOT NULL,
            email_address VARCHAR(100) NOT NULL,
            role_designation VARCHAR(50) NOT NULL,
            password_hash VARCHAR(255) DEFAULT NULL,
            image_url TEXT DEFAULT NULL,
            phone_number VARCHAR(20) DEFAULT NULL,
            action_performed VARCHAR(100) DEFAULT NULL,
            source_account_identifier INT DEFAULT NULL,
            created_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )');

        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_ACCOUNT_ACTION_LOGS_EMAIL ON account_action_logs (LOWER(email_address))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_ACCOUNT_ACTION_LOGS_EMPLOYEE_ID ON account_action_logs (employee_id_number)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_ACCOUNT_ACTION_LOGS_CLERK_USER ON account_action_logs (clerk_user_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_ACCOUNT_ACTION_LOGS_ROLE ON account_action_logs (role_designation)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS account_action_logs');
        $this->addSql('DROP INDEX IF EXISTS UNIQ_ACCOUNTS_ID_NUMBER_NOT_BLANK');
    }
}
