<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260623020000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add analytics action log table for scenario tracing.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("
            CREATE TABLE IF NOT EXISTS analytics_action_logs (
                analytics_action_log_identifier BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                action_key VARCHAR(120) NOT NULL,
                scenario_key VARCHAR(120) DEFAULT NULL,
                action_status VARCHAR(40) NOT NULL,
                action_payload JSONB DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
                PRIMARY KEY (analytics_action_log_identifier)
            )
        ");
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_ANALYTICS_ACTION_LOG_KEY_CREATED ON analytics_action_logs (action_key, created_at)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_ANALYTICS_ACTION_LOG_SCENARIO_CREATED ON analytics_action_logs (scenario_key, created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS analytics_action_logs');
    }
}
