<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260227121901 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('DROP INDEX uniq_accounts_clerk');
        $this->addSql('ALTER TABLE accounts ADD last_login_timestamp TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE accounts ADD failed_login_attempts INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE accounts ADD locked_until_timestamp TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE accounts ALTER account_identifier DROP DEFAULT');
        $this->addSql('ALTER TABLE accounts ALTER account_identifier ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE accounts ALTER last_name TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE accounts ALTER first_name TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE accounts ALTER email_address TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE accounts ALTER role_designation DROP DEFAULT');
        $this->addSql('ALTER TABLE accounts ALTER contact_number TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE accounts ALTER is_active DROP DEFAULT');
        $this->addSql('ALTER TABLE accounts ALTER created_timestamp DROP DEFAULT');
        $this->addSql('ALTER TABLE accounts ALTER updated_timestamp DROP DEFAULT');
        $this->addSql('ALTER INDEX uniq_accounts_email RENAME TO UNIQ_CAC89EACB08E074E');
        $this->addSql('ALTER TABLE audit_logs ALTER audit_log_identifier DROP DEFAULT');
        $this->addSql('ALTER TABLE audit_logs ALTER audit_log_identifier ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE audit_logs ALTER change_details TYPE JSON');
        $this->addSql('ALTER TABLE audit_logs ALTER occurred_timestamp DROP DEFAULT');
        $this->addSql('ALTER TABLE equipment ADD equipment_state VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE equipment ADD schedule_description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE equipment ALTER equipment_identifier DROP DEFAULT');
        $this->addSql('ALTER TABLE equipment ALTER equipment_identifier ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE equipment ALTER total_quantity DROP DEFAULT');
        $this->addSql('ALTER TABLE equipment ALTER available_quantity DROP DEFAULT');
        $this->addSql('ALTER TABLE equipment ALTER operational_status DROP DEFAULT');
        $this->addSql('ALTER TABLE equipment ALTER created_timestamp DROP DEFAULT');
        $this->addSql('ALTER TABLE equipment ALTER updated_timestamp DROP DEFAULT');
        $this->addSql('ALTER TABLE notifications ALTER notification_identifier DROP DEFAULT');
        $this->addSql('ALTER TABLE notifications ALTER notification_identifier ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE notifications ALTER notification_type DROP DEFAULT');
        $this->addSql('ALTER TABLE notifications ALTER is_read DROP DEFAULT');
        $this->addSql('ALTER TABLE notifications ALTER created_timestamp DROP DEFAULT');
        $this->addSql('ALTER TABLE release_returns ALTER release_return_identifier DROP DEFAULT');
        $this->addSql('ALTER TABLE release_returns ALTER release_return_identifier ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE release_returns ALTER transaction_type DROP DEFAULT');
        $this->addSql('ALTER TABLE release_returns ALTER equipment_item_list TYPE JSON');
        $this->addSql('ALTER TABLE release_returns ALTER equipment_item_list DROP DEFAULT');
        $this->addSql('ALTER TABLE release_returns ALTER quantity_processed DROP DEFAULT');
        $this->addSql('ALTER TABLE release_returns ALTER condition_status DROP DEFAULT');
        $this->addSql('ALTER TABLE release_returns ALTER processed_timestamp DROP DEFAULT');
        $this->addSql('ALTER TABLE reservations ADD updated_timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE reservations ALTER reservation_identifier DROP DEFAULT');
        $this->addSql('ALTER TABLE reservations ALTER reservation_identifier ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE reservations ALTER reservation_code TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE reservations ALTER requested_equipment_list TYPE JSON');
        $this->addSql('ALTER TABLE reservations ALTER requested_equipment_list DROP DEFAULT');
        $this->addSql('ALTER TABLE reservations ALTER requested_quantity DROP DEFAULT');
        $this->addSql('ALTER TABLE reservations ALTER purpose_description TYPE VARCHAR(200)');
        $this->addSql('ALTER TABLE reservations ALTER purpose_description SET NOT NULL');
        $this->addSql('ALTER TABLE reservations ALTER activity_type SET NOT NULL');
        $this->addSql('ALTER TABLE reservations ALTER current_status DROP DEFAULT');
        $this->addSql('ALTER TABLE reservations ALTER priority_level TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE reservations ALTER supporting_documents TYPE JSON USING supporting_documents::json');
        $this->addSql('ALTER TABLE reservations ALTER submission_timestamp DROP DEFAULT');
        $this->addSql('ALTER INDEX uniq_reservations_code RENAME TO UNIQ_4DA239612CFDF0');
        $this->addSql('ALTER TABLE tasks ALTER task_identifier DROP DEFAULT');
        $this->addSql('ALTER TABLE tasks ALTER task_identifier ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE tasks ALTER task_type DROP DEFAULT');
        $this->addSql('ALTER TABLE tasks ALTER task_status DROP DEFAULT');
        $this->addSql('ALTER TABLE tasks ALTER created_timestamp DROP DEFAULT');
        $this->addSql('ALTER TABLE tasks ALTER updated_timestamp DROP DEFAULT');
        $this->addSql('ALTER TABLE venues ALTER venue_identifier DROP DEFAULT');
        $this->addSql('ALTER TABLE venues ALTER venue_identifier ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE venues ALTER availability_status DROP DEFAULT');
        $this->addSql('ALTER TABLE venues ALTER created_timestamp DROP DEFAULT');
        $this->addSql('ALTER TABLE venues ALTER updated_timestamp DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE accounts DROP last_login_timestamp');
        $this->addSql('ALTER TABLE accounts DROP failed_login_attempts');
        $this->addSql('ALTER TABLE accounts DROP locked_until_timestamp');
        $this->addSql('ALTER TABLE accounts ALTER account_identifier SET DEFAULT nextval(\'accounts_account_identifier_seq\'::regclass)');
        $this->addSql('ALTER TABLE accounts ALTER account_identifier DROP IDENTITY');
        $this->addSql('ALTER TABLE accounts ALTER last_name TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE accounts ALTER first_name TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE accounts ALTER email_address TYPE VARCHAR(180)');
        $this->addSql('ALTER TABLE accounts ALTER role_designation SET DEFAULT \'Borrower\'');
        $this->addSql('ALTER TABLE accounts ALTER contact_number TYPE VARCHAR(30)');
        $this->addSql('ALTER TABLE accounts ALTER created_timestamp SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE accounts ALTER updated_timestamp SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE accounts ALTER is_active SET DEFAULT true');
        $this->addSql('CREATE UNIQUE INDEX uniq_accounts_clerk ON accounts (clerk_user_id)');
        $this->addSql('ALTER INDEX uniq_cac89eacb08e074e RENAME TO uniq_accounts_email');
        $this->addSql('ALTER TABLE audit_logs ALTER audit_log_identifier SET DEFAULT nextval(\'audit_logs_audit_log_identifier_seq\'::regclass)');
        $this->addSql('ALTER TABLE audit_logs ALTER audit_log_identifier DROP IDENTITY');
        $this->addSql('ALTER TABLE audit_logs ALTER change_details TYPE JSONB');
        $this->addSql('ALTER TABLE audit_logs ALTER occurred_timestamp SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE equipment DROP equipment_state');
        $this->addSql('ALTER TABLE equipment DROP schedule_description');
        $this->addSql('ALTER TABLE equipment ALTER equipment_identifier SET DEFAULT nextval(\'equipment_equipment_identifier_seq\'::regclass)');
        $this->addSql('ALTER TABLE equipment ALTER equipment_identifier DROP IDENTITY');
        $this->addSql('ALTER TABLE equipment ALTER total_quantity SET DEFAULT 0');
        $this->addSql('ALTER TABLE equipment ALTER available_quantity SET DEFAULT 0');
        $this->addSql('ALTER TABLE equipment ALTER operational_status SET DEFAULT \'Active\'');
        $this->addSql('ALTER TABLE equipment ALTER created_timestamp SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE equipment ALTER updated_timestamp SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE notifications ALTER notification_identifier SET DEFAULT nextval(\'notifications_notification_identifier_seq\'::regclass)');
        $this->addSql('ALTER TABLE notifications ALTER notification_identifier DROP IDENTITY');
        $this->addSql('ALTER TABLE notifications ALTER notification_type SET DEFAULT \'Info\'');
        $this->addSql('ALTER TABLE notifications ALTER is_read SET DEFAULT false');
        $this->addSql('ALTER TABLE notifications ALTER created_timestamp SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE release_returns ALTER release_return_identifier SET DEFAULT nextval(\'release_returns_release_return_identifier_seq\'::regclass)');
        $this->addSql('ALTER TABLE release_returns ALTER release_return_identifier DROP IDENTITY');
        $this->addSql('ALTER TABLE release_returns ALTER transaction_type SET DEFAULT \'Release\'');
        $this->addSql('ALTER TABLE release_returns ALTER equipment_item_list TYPE JSONB');
        $this->addSql('ALTER TABLE release_returns ALTER equipment_item_list SET DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE release_returns ALTER quantity_processed SET DEFAULT 0');
        $this->addSql('ALTER TABLE release_returns ALTER condition_status SET DEFAULT \'Good\'');
        $this->addSql('ALTER TABLE release_returns ALTER processed_timestamp SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE reservations DROP updated_timestamp');
        $this->addSql('ALTER TABLE reservations ALTER reservation_identifier SET DEFAULT nextval(\'reservations_reservation_identifier_seq\'::regclass)');
        $this->addSql('ALTER TABLE reservations ALTER reservation_identifier DROP IDENTITY');
        $this->addSql('ALTER TABLE reservations ALTER reservation_code TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE reservations ALTER requested_equipment_list TYPE JSONB');
        $this->addSql('ALTER TABLE reservations ALTER requested_equipment_list SET DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE reservations ALTER requested_quantity SET DEFAULT 0');
        $this->addSql('ALTER TABLE reservations ALTER purpose_description TYPE TEXT');
        $this->addSql('ALTER TABLE reservations ALTER purpose_description DROP NOT NULL');
        $this->addSql('ALTER TABLE reservations ALTER activity_type DROP NOT NULL');
        $this->addSql('ALTER TABLE reservations ALTER current_status SET DEFAULT \'Pending Review\'');
        $this->addSql('ALTER TABLE reservations ALTER priority_level TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE reservations ALTER supporting_documents TYPE TEXT');
        $this->addSql('ALTER TABLE reservations ALTER submission_timestamp SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER INDEX uniq_4da239612cfdf0 RENAME TO uniq_reservations_code');
        $this->addSql('ALTER TABLE tasks ALTER task_identifier SET DEFAULT nextval(\'tasks_task_identifier_seq\'::regclass)');
        $this->addSql('ALTER TABLE tasks ALTER task_identifier DROP IDENTITY');
        $this->addSql('ALTER TABLE tasks ALTER task_type SET DEFAULT \'Preparation\'');
        $this->addSql('ALTER TABLE tasks ALTER task_status SET DEFAULT \'Pending\'');
        $this->addSql('ALTER TABLE tasks ALTER created_timestamp SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE tasks ALTER updated_timestamp SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE venues ALTER venue_identifier SET DEFAULT nextval(\'venues_venue_identifier_seq\'::regclass)');
        $this->addSql('ALTER TABLE venues ALTER venue_identifier DROP IDENTITY');
        $this->addSql('ALTER TABLE venues ALTER availability_status SET DEFAULT \'Available\'');
        $this->addSql('ALTER TABLE venues ALTER created_timestamp SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE venues ALTER updated_timestamp SET DEFAULT CURRENT_TIMESTAMP');
    }
}
