<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260623010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add analytics configuration, run, and result storage tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("
            CREATE TABLE IF NOT EXISTS analytics_configurations (
                analytics_configuration_identifier BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                config_key VARCHAR(120) NOT NULL,
                config_payload JSONB NOT NULL,
                is_active BOOLEAN DEFAULT TRUE NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
                PRIMARY KEY (analytics_configuration_identifier)
            )
        ");
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_ANALYTICS_CONFIG_KEY_ACTIVE ON analytics_configurations (config_key, is_active)');

        $this->addSql("
            CREATE TABLE IF NOT EXISTS analytics_runs (
                analytics_run_identifier BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                run_identifier VARCHAR(64) NOT NULL,
                run_type VARCHAR(80) NOT NULL,
                status VARCHAR(40) NOT NULL,
                triggered_by VARCHAR(80) NOT NULL,
                config_snapshot JSONB DEFAULT NULL,
                summary_payload JSONB DEFAULT NULL,
                error_message TEXT DEFAULT NULL,
                started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (analytics_run_identifier)
            )
        ");
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_ANALYTICS_RUN_IDENTIFIER ON analytics_runs (run_identifier)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_ANALYTICS_RUN_STATUS_STARTED ON analytics_runs (status, started_at)');

        $this->addSql("
            CREATE TABLE IF NOT EXISTS analytics_results (
                analytics_result_identifier BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                run_identifier VARCHAR(64) NOT NULL,
                result_type VARCHAR(80) NOT NULL,
                model_name VARCHAR(120) NOT NULL,
                result_payload JSONB NOT NULL,
                generated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (analytics_result_identifier)
            )
        ");
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_ANALYTICS_RESULT_TYPE_GENERATED ON analytics_results (result_type, generated_at)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_ANALYTICS_RESULT_RUN_IDENTIFIER ON analytics_results (run_identifier)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS analytics_results');
        $this->addSql('DROP TABLE IF EXISTS analytics_runs');
        $this->addSql('DROP TABLE IF EXISTS analytics_configurations');
    }
}
