<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260719010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Remove audit trail storage by dropping the audit_logs table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS audit_logs');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE audit_logs (
            audit_log_identifier INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            performed_by_account_id INT DEFAULT NULL,
            action_performed VARCHAR(100) NOT NULL,
            target_entity_type VARCHAR(100) NOT NULL,
            target_entity_identifier INT DEFAULT NULL,
            change_details JSON DEFAULT NULL,
            actor_name VARCHAR(180) DEFAULT NULL,
            actor_role VARCHAR(80) DEFAULT NULL,
            module_name VARCHAR(120) DEFAULT NULL,
            target_display_label VARCHAR(255) DEFAULT NULL,
            previous_value_json JSONB DEFAULT NULL,
            updated_value_json JSONB DEFAULT NULL,
            reason_remarks TEXT DEFAULT NULL,
            ip_address VARCHAR(80) DEFAULT NULL,
            device_metadata TEXT DEFAULT NULL,
            occurred_timestamp TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY(audit_log_identifier)
        )');
    }
}
