-- ============================================================
-- TechReserve - Complete Database Schema for PGAdmin
-- Run this SQL in PGAdmin Query Tool after connecting to your database
-- ============================================================

-- ===== 1. ACCOUNTS =====
CREATE TABLE IF NOT EXISTS accounts (
    account_identifier INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name VARCHAR(50) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    email_address VARCHAR(100) NOT NULL,
    role_designation VARCHAR(50) NOT NULL DEFAULT 'ROLE_BORROWER',
    contact_number VARCHAR(20) DEFAULT NULL,
    clerk_user_id VARCHAR(255) DEFAULT NULL,
    password_hash VARCHAR(255) DEFAULT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    failed_login_attempts INT NOT NULL DEFAULT 0,
    locked_until_timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    last_login_timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    created_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_accounts_email ON accounts (email_address);

-- ===== Missing columns added to accounts (safe ALTER TABLE) =====
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'pending';
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS is_approved BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS is_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS verification_status VARCHAR(20) NOT NULL DEFAULT 'unverified';
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS invited_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS department VARCHAR(100) DEFAULT NULL;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS invited_by INT DEFAULT NULL REFERENCES accounts(account_identifier) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_accounts_status ON accounts (status);
CREATE INDEX IF NOT EXISTS idx_accounts_clerk_user_id ON accounts (clerk_user_id);
CREATE INDEX IF NOT EXISTS idx_accounts_verification_status ON accounts (verification_status);

-- ===== 2. EQUIPMENT =====
CREATE TABLE IF NOT EXISTS equipment (
    equipment_identifier INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_name VARCHAR(150) NOT NULL,
    category_name VARCHAR(100) NOT NULL,
    total_quantity INT NOT NULL DEFAULT 0,
    available_quantity INT NOT NULL DEFAULT 0,
    operational_status VARCHAR(50) NOT NULL DEFAULT 'Active',
    equipment_state VARCHAR(50) NOT NULL DEFAULT 'Available',
    schedule_description TEXT DEFAULT NULL,
    created_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ===== 3. VENUES =====
CREATE TABLE IF NOT EXISTS venues (
    venue_identifier INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_name VARCHAR(150) NOT NULL,
    venue_location VARCHAR(200) DEFAULT NULL,
    floor_level VARCHAR(50) DEFAULT NULL,
    capacity_limit INT DEFAULT NULL,
    availability_status VARCHAR(50) NOT NULL DEFAULT 'Available',
    description TEXT DEFAULT NULL,
    image_url VARCHAR(500) DEFAULT NULL,
    created_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ===== 4. RESERVATIONS =====
CREATE TABLE IF NOT EXISTS reservations (
    reservation_identifier INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_code VARCHAR(20) NOT NULL,
    borrower_account_id INT NOT NULL,
    organization_name VARCHAR(200) NOT NULL,
    venue_identifier INT DEFAULT NULL,
    requested_equipment_list JSON NOT NULL DEFAULT '[]',
    requested_quantity INT NOT NULL DEFAULT 0,
    event_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    purpose_description VARCHAR(200) NOT NULL,
    activity_type VARCHAR(100) NOT NULL,
    current_status VARCHAR(50) NOT NULL DEFAULT 'Pending Review',
    priority_level VARCHAR(20) DEFAULT NULL,
    rejection_reason TEXT DEFAULT NULL,
    supporting_documents JSON DEFAULT NULL,
    submission_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_reservations_code ON reservations (reservation_code);

-- ===== 5. RELEASE & RETURNS =====
CREATE TABLE IF NOT EXISTS release_returns (
    release_return_identifier INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_identifier INT NOT NULL,
    transaction_type VARCHAR(50) NOT NULL DEFAULT 'Release',
    equipment_item_list JSON NOT NULL DEFAULT '[]',
    quantity_processed INT NOT NULL DEFAULT 0,
    condition_status VARCHAR(50) NOT NULL DEFAULT 'Good',
    remarks_description TEXT DEFAULT NULL,
    processed_by_account_id INT DEFAULT NULL,
    processed_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ===== 6. TASKS =====
CREATE TABLE IF NOT EXISTS tasks (
    task_identifier INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_identifier INT DEFAULT NULL,
    task_title VARCHAR(200) NOT NULL,
    task_description TEXT DEFAULT NULL,
    task_type VARCHAR(50) NOT NULL DEFAULT 'Preparation',
    task_status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    assigned_to_account_id INT DEFAULT NULL,
    due_date_timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    created_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ===== 7. AUDIT LOGS =====
CREATE TABLE IF NOT EXISTS audit_logs (
    audit_log_identifier INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performed_by_account_id INT DEFAULT NULL,
    action_performed VARCHAR(100) NOT NULL,
    target_entity_type VARCHAR(100) NOT NULL,
    target_entity_identifier INT DEFAULT NULL,
    change_details JSON DEFAULT NULL,
    occurred_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ===== 8. NOTIFICATIONS =====
CREATE TABLE IF NOT EXISTS notifications (
    notification_identifier INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_account_id INT NOT NULL,
    notification_title VARCHAR(200) NOT NULL,
    notification_message TEXT DEFAULT NULL,
    notification_type VARCHAR(50) NOT NULL DEFAULT 'Info',
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ===== 9. PENDING USERS (formerly in Supabase) =====
CREATE TABLE IF NOT EXISTS pending_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    department VARCHAR(255) DEFAULT NULL,
    organization VARCHAR(255) DEFAULT NULL,
    phone VARCHAR(20) DEFAULT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    rejection_reason TEXT DEFAULT NULL,
    invitation_token VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    rejected_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    CONSTRAINT status_check CHECK (status IN ('pending', 'approved', 'rejected'))
);

CREATE INDEX IF NOT EXISTS idx_pending_users_email ON pending_users(email);
CREATE INDEX IF NOT EXISTS idx_pending_users_status ON pending_users(status);

-- ===== 10. INVITATIONS (formerly in Supabase) =====
CREATE TABLE IF NOT EXISTS invitations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL,
    invited_by VARCHAR(255) NOT NULL,
    organization VARCHAR(255) DEFAULT NULL,
    invitation_token VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    accepted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    CONSTRAINT invitation_status_check CHECK (status IN ('pending', 'accepted', 'expired'))
);

CREATE INDEX IF NOT EXISTS idx_invitations_email ON invitations(email);
CREATE INDEX IF NOT EXISTS idx_invitations_token ON invitations(invitation_token);
CREATE INDEX IF NOT EXISTS idx_invitations_status ON invitations(status);

-- ===== 11. MESSENGER MESSAGES (Symfony internal) =====
CREATE TABLE IF NOT EXISTS messenger_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body TEXT NOT NULL,
    headers TEXT NOT NULL,
    queue_name VARCHAR(190) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    available_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    delivered_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_messenger_messages_queue ON messenger_messages (queue_name, available_at, delivered_at, id);


-- ============================================================
-- SEED DATA (Optional - Default admin and borrower accounts)
-- ============================================================

INSERT INTO accounts (last_name, first_name, email_address, role_designation, contact_number, is_active, created_timestamp, updated_timestamp, failed_login_attempts)
VALUES 
    ('Admin', 'System', 'admin@techreserve.com', 'ROLE_ADMIN', '09123456789', true, NOW(), NOW(), 0),
    ('Doe', 'John', 'john.doe@example.com', 'ROLE_BORROWER', '09123456788', true, NOW(), NOW(), 0)
ON CONFLICT (email_address) DO NOTHING;
